var TrelloPowerUp = window.TrelloPowerUp;

var listasBloqueadas = [
  "AVALÚOS PENDIENTES ENVIAR",
  "AVALÚOS PENDIENTES SUPERVISIÓN ERICK",
  "AVALÚOS PENDIENTES COTIZACIÓN ERICK",
  "AVALUOS PENDIENTES DE SUPERVICIÓN JULIO",
  "AVALÚO PENDIENTES DE COTIZACIÓN JULIO",
  "AVALÚOS FINALIZADOS",
  "ESPERA DE PROPUESTA INS",
  "REVISIÓN DE PROPUESTA/AVALUO Y APELACIONES",
  "ESPERANDO REPUESTOS ASEGURADORAS PRIVADAS",
  "EN COMPRA DE REPUESTOS",
  "COMPRAS REALIZADAS Y P.E PENDIENTES",
  "DECLINADOS / NO REPARADOS",
  "PARA INGRESAR A REPARACIÓN",
  "INGRESOS",
  "ENDEREZADO",
  "ALISTADO",
  "ARMADO Y PULIDO",
  "LISTO PARA ENTREGA",
  "VEHÍCULOS REPARACIÓN EXTERNA AL TALLER 3B",
  "ENTREGADO EN PROCESO DE COBRO INS / PJ ANDY",
  "ENTREGADO EN COBRO ASEGURADORAS NATY",
  "ENTREGADO EN COBRO PARTICULARES NATY",
  "ENTREGADOS CON REPUESTOS PENDIENTES",
  "ENTREGADOS ADICIONAL PENDI. ASEGURADORAS M.O. Y REPUESTOS ERICK - JULIO",
  "REINGRESO A TALLER PARA INSTALAR PIEZAS PENDIENTES",
  "COBRADOS EN PROCESO DE LIQUIDAR Y ARCHIVO MARY - casos cancelados"
];

TrelloPowerUp.initialize({
  'list-move': function (t, options) {
    if (listasBloqueadas.includes(options.list.name)) {
      return t.alert({
        message: "🚫 Esta lista está bloqueada y no puede moverse.",
        duration: 5
      });
    }
    return true;
  }
});
